# Generated by Django 3.0.8 on 2020-08-02 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Minimal', 'Minimal'), ('Per_km', 'Per km')], max_length=50, verbose_name='Type')),
                ('value', models.IntegerField(default=0, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Delivery payment',
                'verbose_name_plural': 'Delivery payments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('description_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('description_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock quantity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.Category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
