# Generated by Django 3.0.8 on 2020-08-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPayment',
        ),
    ]
