# Generated by Django 3.0.8 on 2020-08-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
    ]
