# Generated by Django 3.0.8 on 2020-08-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayOff',
        ),
    ]
